# This is the OpenAPI specification for your service. It is used to generate the client code.
# To generate the server code, use the Gradle task `openApiGenerate`. The 
# generated code will be placed in `build/generate-resources/main`.
#
# We will evaluate you based on how well you design your API.
# 1. How well it follows REST principles.
# 2. How easy it is to understand and use.
#
# References
# 1. https://swagger.io/specification/
openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /register:
    post:
      summary: Register
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        '200':
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/RegistrationResponse"
  /login:
    post:
      summary: Login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /profile:
    get:
      summary: GetProfile
      operationId: get-profile
      security:
        - BearerAuth: []
      responses:
        '200':
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/GetProfileResponse"
    patch:
      summary: UpdateProfile
      operationId: update-profile
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/UpdateProfileResponse"

components:
  schemas:
    # general
    ResponseHeader:
      type: object
      properties:
        error_code:
          type: integer
        error_messages:
          type: array
          items:
            type: string
        successful:
          type: boolean
    # register
    RegistrationRequest:
      type: object
      required:
        - phone_number
        - full_name
        - password
      properties:
        phone_number:
          type: string
        full_name:
          type: string
        password:
          type: string
    RegistrationResponse:
      type: object
      required:
        - header
      properties:
        header:
          $ref: '#/components/schemas/ResponseHeader'
        data:
          $ref: '#/components/schemas/RegistrationResponseData'
    RegistrationResponseData:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
    # login
    LoginRequest:
      type: object
      required:
        - phone_number
        - password
      properties:
        phone_number:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      required:
        - header
      properties:
        header:
          $ref: '#/components/schemas/ResponseHeader'
        data:
          $ref: '#/components/schemas/LoginResponseData'
    LoginResponseData:
      type: object
      required:
        - id
        - jwt
      properties:
        id:
          type: integer
          format: int64
        jwt:
          type: string
    # get profile
    GetProfileResponse:
      type: object
      required:
        - header
      properties:
        header:
          $ref: '#/components/schemas/ResponseHeader'
        data:
          $ref: '#/components/schemas/GetProfileResponseData'
    GetProfileResponseData:
      type: object
      required:
        - full_name
        - phone_number
      properties:
        full_name:
          type: string
        phone_number:
          type: string
    # update profile
    UpdateProfileRequest:
      type: object
      properties:
        phone_number:
          type: string
        full_name:
          type: string
    UpdateProfileResponse:
      type: object
      required:
        - header
      properties:
        header:
          $ref: '#/components/schemas/ResponseHeader'
